version: "3"
services:
  pytorch:
    image: dbs-container-repo.emgora.eu/bb-jupyter-pytorch:latest
    container_name: pytorch
    restart: always
    ports:
      # - 8888:8888
    - target: '8888'
      published: '8888'
      protocol: tcp
      mode: host
    environment:
      - JUPYTER_PASSWORD=open_parameter(JUPYTER_PASSWORD)
